### ISSUE TITLE
Feature parity with r-lib/actions

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/rig#24]
For `setup-r`:

- [x] Linux support (#7)
- [x] Remove `-fopenmp` flag on macOS (#13)
- [x] Set up RSPM (#15)
- [x] Add Rscript to the PATH (#20)
- [x] Update Rtools40 (#14)
- [x] Set default CRAN mirror to cloud, in addition to RSPM, potentially (#11) 
- [x] Install gfortran on macOS (#21)
- [x] Install system utilities on macOS (#22)
- [x] Support Rtools42 on Windows (#23)

EDIT: we don't necessarily need these now, they can be implemented later:

For `setup-pandoc`:
- [x] ~~Install pandoc (#16)~~

For `setup-tinytex`:
- [x] ~~Install tinytex (#17)~~
